dist: precise
sudo: false

language: java

jdk:
  - openjdk7
  #- openjdk6    Issues with hDF5 libraries
  - oraclejdk7
  - oraclejdk8


install:
    - export main_repo_branch=$TRAVIS_BRANCH
    - if [[ ${main_repo_branch} != "master" && ${main_repo_branch} != "development" && ${main_repo_branch} != "experimental" ]]; then main_repo_branch=development ; fi
    
    - git clone https://github.com/NeuroML/NeuroML2.git
    - cd NeuroML2
    - git checkout $main_repo_branch
    - mvn install
    - cd ..
    
    - git clone https://github.com/NeuroML/org.neuroml.model.injectingplugin.git
    - cd org.neuroml.model.injectingplugin
    - git checkout $main_repo_branch
    - mvn install
    - cd ..
    
    
    
    
    
 
