# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:  [ master, development, experimental, osb* ]
  pull_request:
    branches:  [ master, development, experimental, osb* ]

jobs:
  build_and_test:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:        
        java: [ '8', '11', '16', '17' ]
        runs-on: [ubuntu-latest, macos-11, windows-latest]

    name: Test on Java ${{ matrix.Java }} on ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.Java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.Java }}
        distribution: 'temurin'
        
    - name: Install and test (non Win)
      if: ${{ matrix.runs-on != 'windows-latest' }}
      run: |
        # Install org.neuroml.model.injectingplugin
        export main_repo_branch=${GITHUB_REF##*/}
        echo Using branch $main_repo_branch
        git clone https://github.com/NeuroML/org.neuroml.model.injectingplugin.git
        cd org.neuroml.model.injectingplugin
        git checkout $main_repo_branch
        mvn install
        cd ..
        
        # Install NeuroML2
        export main_repo_branch=${GITHUB_REF##*/}
        echo Using branch $main_repo_branch
        git clone https://github.com/NeuroML/NeuroML2.git
        cd NeuroML2
        git checkout $main_repo_branch
        mvn install
        cd ..
        
        # Install this package and test with Maven
        pwd
        mvn install
        mvn dependency:tree
        
    - name: Install and test (Win)
      if: ${{ matrix.runs-on == 'windows-latest' }}
      run: |
        # Install org.neuroml.model.injectingplugin
        echo Using branch $env:GITHUB_REF_NAME
        git clone https://github.com/NeuroML/org.neuroml.model.injectingplugin.git
        cd org.neuroml.model.injectingplugin
        git checkout $env:GITHUB_REF_NAME
        mvn install
        cd ..
        
        # Install NeuroML2
        echo Using branch $env:GITHUB_REF_NAME
        git clone https://github.com/NeuroML/NeuroML2.git
        cd NeuroML2
        git checkout $env:GITHUB_REF_NAME
        mvn install
        cd ..
        
        # Install this package and test with Maven
        pwd
        mvn install
        mvn dependency:tree
